filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/snort/alert_json.txt
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      log_type: snort

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true

output.logstash:
  hosts: ["localhost:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
